{
 "title": "EndUser Response Time",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "EndUser Total Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "navigation_timing_load_event_end_seconds{instance=~\"$service\",job=\"webdriver\"}-navigation_timing_start_seconds{instance=~\"$service\",job=\"webdriver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Enduser Network Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "navigation_timing_response_end_seconds{instance=~\"$service\",job=\"webdriver\"}-navigation_timing_domain_lookup_start_seconds{instance=~\"$service\",job=\"webdriver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Enduser Browser Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "navigation_timing_load_event_end_seconds{instance=~\"$service\",job=\"webdriver\"}-navigation_timing_dom_loading_seconds{instance=~\"$service\",job=\"webdriver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}