apiVersion: charts.helm.k8s.io/v1alpha1
kind: Xl
metadata:
  name: xl-release
spec:
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic

  global:
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 7.21.3
    #externalIP: 10.0.2.15
  nginxingress:
    enabled: false
  control:
    enabled: false
  platform:
    enabled: false
  grafana:
    enabled: true
    adminPassword: grafana
  prometheus:
    enabled: true
    nodeExporter:
      enabled: false
    extraScrapeConfigs: |
          - job_name: 'webdriver'
            metrics_path: /probe
            static_configs:
              - targets:
                - https://10.16.172.11/u/app/index.html
                - https://10.16.172.12/u/app/index.html

            relabel_configs:
              - source_labels: [__address__]
                regex: (.*)(:80)?
                target_label: __param_target
                replacement: ${1}
              - source_labels: [__param_target]
                regex: (.*)
                target_label: instance
                replacement: ${1}
              - source_labels: []
                regex: .*
                target_label: __address__
                replacement: webdriver:9156  # WebDriver Exporter
