# Default values for webdriver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: turbonomic
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
